/* tslint:disable */
/* eslint-disable */
export function start(): void;
export function __wbg_worldstate_free(a: number): void;
export function worldstate_new(): number;
export function worldstate_init(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function worldstate_update(a: number, b: number, c: number): number;
export function worldstate_inlay_hints(a: number): number;
export function worldstate_completions(a: number, b: number, c: number): number;
export function worldstate_hover(a: number, b: number, c: number): number;
export function worldstate_code_lenses(a: number): number;
export function worldstate_references(a: number, b: number, c: number, d: number): number;
export function worldstate_prepare_rename(a: number, b: number, c: number): number;
export function worldstate_rename(a: number, b: number, c: number, d: number, e: number): number;
export function worldstate_signature_help(a: number, b: number, c: number): number;
export function worldstate_definition(a: number, b: number, c: number): number;
export function worldstate_type_definition(a: number, b: number, c: number): number;
export function worldstate_document_symbols(a: number): number;
export function worldstate_type_formatting(a: number, b: number, c: number, d: number): number;
export function worldstate_folding_ranges(a: number): number;
export function worldstate_goto_implementation(a: number, b: number, c: number): number;
export function __wbg_wbg_rayon_poolbuilder_free(a: number): void;
export function wbg_rayon_poolbuilder_numThreads(a: number): number;
export function wbg_rayon_poolbuilder_receiver(a: number): number;
export function wbg_rayon_poolbuilder_build(a: number): void;
export function wbg_rayon_start_worker(a: number): void;
export function initThreadPool(a: number): number;
export const memory: WebAssembly.Memory;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
export function __wbindgen_start(): void;
