import type {ServiceOptionsWithErrorMessages} from "ace-linters/src/types/language-service";
import type {CSpellUserSettings} from "@cspell/cspell-types";

export interface AceSpellCheckOptions extends ServiceOptionsWithErrorMessages{
  spellCheckOptions?: CSpellUserSettings;
  /**
   * Base URL used to fetch lazy dictionary assets generated by build-cspell-dicts.js.
   * Example: https://cdn.example.com/ace-spell-check/dicts
   */
  dictBaseUrl?: string;
  /**
   * Optional explicit mapping from dictionary package name to asset URL.
   * Example: { "@cspell/dict-java": "/assets/dicts/cspell-dict-java.json" }
   */
  dictAssetUrls?: Record<string, string>;
  /**
   * When true and spellCheckOptions.dictionaries is not explicitly set, include all bundled default dictionaries.
   * This increases lazy-loaded dictionary traffic but matches full bundled dictionary behavior.
   */
  enableAllDefaultDictionaries?: boolean;
}
