import type {ServiceOptionsWithErrorMessages} from "ace-linters/src/types/language-service";
import type {CSpellUserSettings} from "@cspell/cspell-types";

export interface AceSpellCheckOptions extends ServiceOptionsWithErrorMessages {
    /**
     * Those options would be merged with default cspell settings
     */
    spellCheckOptions?: CSpellUserSettings;
    /**
     * Base URL used to fetch lazy dictionary assets generated by build-cspell-dicts.js.
     * Example: https://cdn.example.com/ace-spell-check/dicts
     */
    dictBaseUrl?: string;
    /**
     * Optional explicit mapping from dictionary package name to asset URL.
     * Example: { "@cspell/dict-java": "/assets/dicts/cspell-dict-java.json" }
     */
    dictAssetUrls?: Record<string, string>;
    /**
     * Enables document-scoped dictionary configuration and loading.
     *
     * When true (default), dictionaries are filtered for the current document
     * (languageId + matching overrides) before loading and validation.
     *
     * Set to false to use only global dictionary references (plus matching filename overrides),
     * without languageId-based dictionary expansion.
     * @default true
     */
    documentScopedDictionaries?: boolean;
}

